# Generated by Django 5.1.5 on 2025-02-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0002_alter_chatgptbot_options_chatgptbot_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgptbot',
            options={'ordering': ['created_at'], 'verbose_name': 'Messages History', 'verbose_name_plural': 'Messages History'},
        ),
    ]
