# Generated by Django 5.1.5 on 2025-02-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0003_alter_chatgptbot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptbot',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
